document.title="CHARACTERS";document.addEventListener("DOMContentLoaded",()=>{const e=document.getElementById("global-nav");if(!e)return;const t=[{name:"HOLLY CALLAHAN",url:"bonabi.html"},{name:"TRIXIE SHERMAN",url:"mangle.html"},{name:"JOSHUA WOODSIDE",url:"joshua.html"},{name:"OSCAR WOODSIDE",url:"oscar.html"},{name:"VICTOR CALLAHAN",url:"victor.html"}],a=[{name:"ADORA",url:"adora.html"},{name:"DOMINIC",url:"dom.html"},{name:"RYO",url:"ryo.html"},{name:"THEO",url:"theo.html"},{name:"WILLIAM AFTON",url:"afton.html"}],n=window.location.pathname,l=n.substring(n.lastIndexOf("/")+1)||"bonabi.html",s=typeof currentCharacterData!="undefined"&&currentCharacterData.isAliveSubject===!0,r=s?"alive.html":"dead.html",c=s?"[ ALIVE ]":"[ DEAD ]",i=s?"alive-label":"dead-label",o=s?a:t;let m=`<a onclick="fadeTo('${r}')" class="nav-btn submenu-btn">< SELECTION MENU</a>`;m+=`<div class="nav-status-group"><span class="group-label ${i}">${c}</span>`,o.forEach(e=>{const t=l.toLowerCase()===e.url.toLowerCase()?"active":"";m+=`<a onclick="fadeTo('${e.url}')" class="nav-btn ${t}">${e.name}</a>`}),m+="</div>",e.innerHTML=m,setTimeout(()=>{document.querySelectorAll(".nav-btn, .submenu-btn, .collapsible-header, .audio-control-btn").forEach(e=>{e&&e.addEventListener("mouseenter",()=>{typeof playHoverSound=="function"&&playHoverSound()})})},20);const d=document.createElement("style");d.innerHTML=".lore-text, .list-spacing, .toggle-content { white-space: pre-line !important; padding: 0 !important; margin: 0 !important; padding-left: 5px !important; text-align: left !important; }",document.head.appendChild(d),typeof currentCharacterData!="undefined"&&renderCharacter(currentCharacterData);

// 🎯 核心防護鎖：如果當前頁面不是 ryo.html，強制將網頁內外任何隱藏的音樂開關與音訊播放完全格式化切斷！
if(l.toLowerCase()!=="ryo.html"){
    const musicToggle = document.getElementById("music-toggle") || document.getElementById("music-toggle-text") || document.querySelector(".audio-control-btn");
    if(musicToggle) musicToggle.remove(); // ❌ 徹底拔除畫面上的 MUSIC 開關按鈕
    const globalBgm = document.getElementById("bgm") || document.getElementById("audio") || document.querySelector("audio");
    if(globalBgm) { globalBgm.pause(); globalBgm.src = ""; globalBgm.remove(); } // ❌ 強制將可能殘留或全域誤載的音訊停止、清空並蒸發
}

setTimeout(()=>{document.body&&document.body.classList.add("fade-in")},10)});function renderCharacter(e){let t="";e.notes&&Array.isArray(e.notes)&&(t=e.notes.map((e,t)=>`<div class="small-note">${t+1}. ${e}</div>`).join(""));const a=document.getElementById("view-layout");if(!a)return;const n=e.isAliveSubject?"LOCATION:":"DIED:",l=e.isAliveSubject?"Hurricane, Utah":e.died;let s=`<tr><td class="label">Name</td><td>${e.name}</td></tr><tr><td class="label">Alias</td><td>${e.alias}</td></tr><tr><td class="label">Gender</td><td>${e.gender}</td></tr><tr><td class="label">${n}</td><td>${l}</td></tr>`;e.killedBy&&(s+=`<tr><td class="label">Killed by</td><td>${e.killedBy}</td></tr>`),a.className="wiki-layout",a.innerHTML=`<div class="wiki-infobox"><div class="infobox-title" style="color: ${e.titleColor}; border-bottom-color: ${e.titleColor};">${e.name}</div><img src="${e.pfp}" class="infobox-pfp" onerror="this.src='https://placehold.co'"><table class="infobox-table">${s}</table></div><div class="lore-content-area"><h1 style="color: ${e.titleColor}">${e.name}</h1><div class="quote-block">"${e.quote}"</div><h2 class="collapsible-header" onclick="toggleSection(this)">PURPOSE</h2><div class="toggle-content" style="display: none;"><div class="lore-text">${e.purpose}</div></div><h2 class="collapsible-header" onclick="toggleSection(this)">BACKGROUND</h2><div class="toggle-content" style="display: none;"><div class="lore-text">${e.bg}</div></div><h2 class="collapsible-header" onclick="toggleSection(this)">PERSONALITY</h2><div class="toggle-content" style="display: none;"><div class="lore-text">${e.pers}</div></div><h2 class="collapsible-header" onclick="toggleSection(this)">LIKES</h2><div class="toggle-content" style="display: none;"><div class="lore-text">${e.likes}</div></div><h2 class="collapsible-header" onclick="toggleSection(this)">DISLIKES</h2><div class="toggle-content" style="display: none;"><div class="lore-text">${e.dislikes}</div></div><h2 class="collapsible-header" onclick="toggleSection(this)">RELATIONSHIPS</h2><div class="toggle-content" style="display: none;"><div class="lore-text">${e.rel}</div></div><h2 class="collapsible-header" onclick="toggleSection(this)">NOTES</h2><div class="toggle-content" style="display: none;"><div class="list-spacing">${t}</div></div></div>`,setTimeout(()=>{a.querySelectorAll(".collapsible-header").forEach(e=>{e.addEventListener("mouseenter",()=>{typeof playHoverSound=="function"&&playHoverSound()})})},10)}function toggleSection(e){const t=e.nextElementSibling;t.style.display="none"===t.style.display||""===t.style.display?"block":"none"}function fadeTo(e){document.body&&(document.body.classList.remove("fade-in"),document.body.classList.add("fade-out"));let t="index.html"===e?"lobby.html":e;setTimeout(()=>{window.location.href=t},450)}
